# Configuration de la sécurité
security:
  endpoints:
    permitAll:
      - /api/auth/set-password
      - /api/auth/login
      - /api/auth/create-password-reset-token
      - /api/auth/create-password-token
      - /api/auth/get-email
      - /api/auth/get-email-from-reset-token
      - /api/companies/company/{companyId}
      - /api/auth/forgot-password
      - /api/auth/reset-password
    authenticatedCompany: /api/companies/company/get/{companyId}
    logout: /api/auth/logout

# Configuration de la gateway
gateway:
  company-service:
    public:
      - /api/companies/register
      - /api/companies/company/complete
      - /api/companies/get/all/waiting
    protected:
      - /api/companies/**
      - /api/strategicAxes/**
      - /api/site/**
      - /api/department/**
      - /api/domain/**
      - /api/qualification/**
  auth-service:
    public:
      - /api/auth/register
      - /api/auth/set-password
      - /api/auth/login
      - /api/auth/get-email
      - /api/auth/get-email-from-reset-token
      - /api/auth/forgot-password
      - /api/auth/reset-password
    protected:
      - /api/auth/**
      - /api/users/**
      - /api/groupes/**
  collaborator-service:
    protected:
      - /api/collaborator/**
  notification-service:
    public:
      - /api/notifications/**